### ISSUE TITLE
关于设置颜色的问题

### ISSUE THREAD

**Issue by cwangzh** [tuteng/MPAndroidChart#3]
你好，想了解下，使用折线图的时候，那个填充颜色如何设置成渐变的。

能不能给出具体实现代码？谢谢

**Comment by tuteng** [comment]
是折线的颜色吗。

**Comment by cwangzh** [comment]
折线图设置的填充色   FillColor  能不能从上到下  渐变？

**Comment by tuteng** [comment]
https://play.google.com/store/apps/details?id=com.xxmassdeveloper.mpchartexample&hl=zh_CN&referrer=utm_source%3Dgoogle%26utm_medium%3Dorganic%26utm_term%3Dmpandroidchart&pcampaignid=APPU_1_Lut_Vd7qAo-yoQTZprbwBQ
这个demo里没有找到你说的那种效果

**Comment by cwangzh** [comment]
没有。 就是这张图片  下面的部分  想设置成渐变色 。有办法吗？

![1111111](https://cloud.githubusercontent.com/assets/7898476/8180140/7c36da60-144e-11e5-92af-655f16e56fd6.png)

**Comment by tuteng** [comment]
我没有做过这种效果，你要不试试 https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/StackedBarActivity.java 这个

**Comment by cwangzh** [comment]
没发现有什么特别的，那个就是设置的单一颜色吧？
